### ISSUE TITLE
[1.10.2 - V1.2.4] Crash on entering portal

### ISSUE THREAD

**Issue by VallenFrostweaver** [superdextor/Ad-Inferos-Mod#1]
Spawned in dark bricks and wither dust, used them to make the portal in a snowy biome in the Craft of the Titans modpack and upon entering the portal crashed and can't recover.  See pastebin below for crash report. If you believe it's another mod please let me know and I will report there.

https://pastebin.com/Np44MBS8

**Comment by superdextor** [comment]
It appears that Actually Additions is to blame.
The mod attempted to modify the Abyss terrain and was unsuccessful.

```
java.lang.IllegalArgumentException
    at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
    at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
    at net.minecraft.world.biome.Biome.plantFlower(Biome.java:459)
    at net.minecraft.block.BlockGrass.func_176474_b(BlockGrass.java:105)
    at de.ellpeck.actuallyadditions.mod.gen.WorldGenLushCaves.genTreesAndTallGrass(WorldGenLushCaves.java:113)
    at de.ellpeck.actuallyadditions.mod.gen.WorldGenLushCaves.generateCave(WorldGenLushCaves.java:54)
    at de.ellpeck.actuallyadditions.mod.gen.WorldGenLushCaves.generate(WorldGenLushCaves.java:37)
    at de.ellpeck.actuallyadditions.mod.gen.OreGen.generateDefault(OreGen.java:85)
    at de.ellpeck.actuallyadditions.mod.gen.OreGen.generate(OreGen.java:63)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
```

**Comment by VallenFrostweaver** [comment]
Thanks! I'll send this that way then. Much appreciation!
