### ISSUE TITLE
Crash when trying to start a server. Singleplayer is working.

### ISSUE THREAD

**Issue by Rinelw** [superdextor/Ad-Inferos-Mod#2]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 25.06.17 15:09
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from §e§k!!§6§k]]§c§kkk§4§lAd Inferos§c§kkk§6§k]]§e§k!! (adinferos)
Caused by: java.lang.NoSuchFieldError: shownTip
	at com.superdextor.adinferos.blocks.BlockHellDoor.<init>(BlockHellDoor.java:23)
	at com.superdextor.adinferos.init.NetherBlocks.<clinit>(NetherBlocks.java:73)
	at com.superdextor.adinferos.AdInferosCore.preInit(AdInferosCore.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1253208120 bytes (1195 MB) / 1699741696 bytes (1621 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 2 total; -Xms1G -Xmx3G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2345 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2345-universal.jar) 
	UCH	forge{13.20.0.2345} [Minecraft Forge] (forge-1.11.2-13.20.0.2345-universal.jar) 
	UCH	thinkbigcore{1.6.1} [§5§m===§r §e§lThink Big Core §5§m===§r] (Think Big Core V1.6.1 - 1.11.2.jar) 
	UCE	adinferos{1.2.6} [§e§k!!§6§k]]§c§kkk§4§lAd Inferos§c§kkk§6§k]]§e§k!!] (Ad Inferos V1.2.6 - 1.11.2.jar) 
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by cursinorock** [comment]
Same here

**Comment by superdextor** [comment]
This is an known Error. A disclaimer was posted [here](https://minecraft.curseforge.com/projects/think-big-core#title-1-1) some time ago. I have a patch put together but I haven't had enough free time to test it and finish everything I want to in the new release. Sorry :/

**Comment by VallenFrostweaver** [comment]
Thanks Superdexter. I understand. I appreciate the info. Free time is sometimes hard to come by.
